KSU: OP15 various changes to compile with ksu
KSU: Allow additional managers
KSU: Fix stackprotector
KSU: Fix base_version
OP15: Add stock kernel 16.0.5.700 date

KSU: Compile error on kernel 6.12
Fix the following compile error on 6.12 kernel
In file included from ../drivers/kernelsu/core/init.c:11:
../drivers/kernelsu/policy/allowlist.h:6:10: fatal error: 'uapi/app_profile.h' file not found
6 | #include "uapi/app_profile.h"